import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
const baseUrl = "https://mocki.io/v1";
// Define the API slice using createApi
export const carApiSlice = createApi({
  reducerPath: "api",
  baseQuery: fetchBaseQuery({ baseUrl: baseUrl }),
  endpoints: (builder) => ({
    getItems: builder.query({
      query: () => `/b8a0d4cb-d74e-43d3-9093-b7bd2e89044b`,
    }),
  }),
});

// Export the endpoint and hooks generated by createApi
export const { useGetItemsQuery } = carApiSlice;
